# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ee87e68c2455fc422f97ec958d35c5adb20622b569014c8ad6086c6c2a5451f619f9ab457c8691791857a5e134b28633b15afb407be14a213776d138cc5bb17b

test:
  secret_key_base: c0b86d5bbc72d64ff4310169ecdbc9f2b7118649a8bf6b723c655a431c3c1cfc23bd5487ff423b9b36153c5165e97e18eebd43944305dd97becb480ac6d87e09

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
